### ISSUE TITLE
Mise à jour des entités mawaqit

### ISSUE THREAD

**Issue by MehdiTouns31** [mawaqit/home-assistant#12]
Salemoua3laykoum l'équipe,
Bon ramadhan à vous.

J'ai remarqué, que chaque jour, à minuit, les entités d'horaires des prières se mettent à jour. Par contre, à l'issue de la mise à jour, les horaires restent inchangées entre avant et après la mise à jour. Et après comparaison avec la mosquée en question sur le site mawaqit, il y a une différence de quelques minutes entre les horaires de mes entités et les horaires de prières de la mosquée. 

Voir l'exemple ci-dessous:
Les horaires de prières de mes entités 
![Screenshot_20220403_004001_io homeassistant companion android](https://user-images.githubusercontent.com/73989636/161403740-b18534db-ae27-4fc2-91df-3f9c495f56bf.jpg)
Les horaires de prières de la mosquée 
![Screenshot_20220403_004011_io homeassistant companion android](https://user-images.githubusercontent.com/73989636/161403784-a7277098-b863-41c8-ba86-437c3a945bcc.jpg)

Peut être qu'il faudrait que la mise à jour se fasse plus tard dans la nuit pour que les horaires de prières des entités soient parfaitement à jour et synchronisé avec celles de leur mosquée respective ?
J'ai remarqué, que plus tard dans la nuit (vers 5h du mat), le fait de recharger l'intégration "mawaqit" permet d'avoir exactement les mêmes horaires de prières que celles de la mosquée. 

Barrakallahufikoum.
Mehdi

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum
Sur l'appli mawaqit et la webmobile on affiche les horaires du lendemain juste après l'isha.
Sur le home-hassitant ce n'est pas le cas

**Comment by MehdiTouns31** [comment]
Salem,

Comment expliques-tu alors que quand je recharge l'intégration mawaqit sur Home Assistant dans une même journée, les horaires des prières évoluent de quelques minutes. Les horaires de prières ne sont pas sensés être fixes au cours d'une même journée ?

**Comment by MehdiTouns31** [comment]
J'illustre mes propos avec cet exemple :
Les horaires de prières à 14h56 :
![Screenshot_20220424_145657_io homeassistant companion android](https://user-images.githubusercontent.com/73989636/164977796-69440167-8463-44d6-a256-613344535dc3.jpg)

Je recharge l'intégration mawaqit pour que les entités mawaqit se mettent à jour. 

Les horaires de prières à 14h57 après le rechargement :
![Screenshot_20220424_145728_io homeassistant companion android](https://user-images.githubusercontent.com/73989636/164977933-113f0878-65b2-4782-859f-f6cd36cb1176.jpg)

Les horaires de prières ont légèrement évoluées après le rechargement de l'intégration. En particulier le Fajr est 2mn plutôt et le Maghrib 1mn plus tard. Ce qui veut dire que ce matin le fajr a adhan 2mn plus tard chez moi... Et ce soir, si je n'avais pas rechargé l'intégration, le Maghrib aurait adhan 1mn plutôt... C'est embêtant pendant ce mois du Ramadhan ce léger décalage des horaires de prières. C'est pourquoi j'insiste auprès de vous pour savoir si vous pouvez corriger cela ? 

Une piste selon moi c'est de modifier la valeur de l'entité "sensor.midnight_time" de "00:00:00" à par exemple "03:00:00" car j'ai l'impression qu'à minuit, c'est trop tôt pour déclencher la mise à jour des entités mawaqit et ça ne fonctionne pas. Par contre à 3h du matin ça paraît plus jouable selon moi.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
On va regarder tout ça insh'Allah

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Je ferme cette issue car on va revoir la partie récupération des horaires. Suivre cette Issue #16

**Comment by MehdiTouns31** [comment]
OK ça marche mes frères. 
Bon courage

**Comment by MehdiTouns31** [comment]
Salemoua3laykoum les freres,
Je vous relance sur ce sujet pour la V2 de mawaqit. Ça serait top d'avoir les sensors des prières qui soient parfaitement à jour.

Je suis disponible pour des tests si besoins. 
Barrakallahufikoum.

Mehdi
