### ISSUE TITLE
This integration does not support user interface configuration

### ISSUE THREAD

**Issue by 09888** [mawaqit/home-assistant#13]

**Comment by 09888** [comment]
I have my home-assistant as Docker container

**Comment by chiccoss** [comment]
Assalamualaikum, same problem , when adding the integration to home assistant an error message shows up, saying, does not support user interface configuration

**Comment by ElSafouane** [comment]
Salam 3aleykoum, I think I have the same problem trying to add Mawaqit as an integration. The Home Assistant console displays a message saying:

"This integration does not support configuration through the user interface. If you followed this link from the Home Assistant website, make sure you are running the latest version of Home Assistant"

![image](https://user-images.githubusercontent.com/72827723/163287399-0e6d3cb1-073f-4020-b153-1181e9f523fb.png)

**Comment by chiccoss** [comment]
Ok, I will test it 👌

**Comment by khorchanov** [comment]
Salam,

Same problem here, I'am on last version 2022.4.4

**Comment by 09888** [comment]
Alsalam I,m on version 22.3.8 ( container )

This schoss be the latest stable version and Mawaqit Prayer Times doesn't work.

**Comment by mouledla** [comment]
Same problem here. I am on last version 2022.4.7.
