### ISSUE TITLE
Use the calendar to get prayer times instead of the times node

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/home-assistant#16]
![image](https://user-images.githubusercontent.com/97339607/170826238-b197cacc-2029-4eaa-9162-02fd8fe55187.png)

**Comment by yac69** [comment]
The last version is based on the calendar json. the prayer times are downloaded once during the installation of the integration and every day at midnight the prayer times are updated based on the calendar json rather than calling again the API.
