### ISSUE TITLE
Add possibility to choose the mosque after login

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/home-assistant#19]

**Comment by yacine-em** [comment]
This was added in V2

**Comment by mseddik** [comment]
Hi, 
The mosque shown are not correct, however the latitude & longitude are read correctly
![image](https://user-images.githubusercontent.com/5212954/196677114-f54846bb-c191-4c1f-826e-7e3c3190e413.png)
