### ISSUE TITLE
Nouvelle entité "temps restant avant l'entrée de la prochaine prière" 

### ISSUE THREAD

**Issue by MehdiTouns31** [mawaqit/home-assistant#20]
Salemoua3laykoum,

Comme je vois qu'il va y avoir un peu de développement, j'en profite pour vous demander si c'est possible d'ajouter une entité du style "next_prayer" qui afficherait le temps restant avant l'entrée de la prochaine prière. Je trouverai cela très pratique. 
Il s'agit du même temps affiché dans la page Web mawaqit voir cadre rouge dans la capture ci dessous : 
![Screenshot_20220528_151955](https://user-images.githubusercontent.com/73989636/170827693-41c92b3c-ec9a-43ca-a7fa-38d8544798d8.jpg)

A voir si c'est fesable pour vous, 
Merci l'équipe.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Quel intérêt sur home assistant ? peux-tu donner des use cases ?

**Comment by MehdiTouns31** [comment]
Dans mon cas, ça serait uniquement pour de l'affichage sur la page d'accueil de mon Lovelace. L'idée c'est de voir en coup d'œil sur cette page, une synthèse de toutes les infos qui remontent sur home assitant y compris le temps restant avant l'entrée de la prochaine prière.

C'est juste un plus mais ce n'est certainement pas indispensable.

**Comment by yac69** [comment]
Salam Aleikom,
c'est tout à fait possible avec une automation ou un blueprints
ci-joint un blueprint que vous pouvez  adapter et mettre dans /config/blueprints/automation/mawaqit/

il permet de notifier (sur tél/enceinte media_player) la prière quand son temps arrive, de faire des actions (lire coran, petite sourats) 10 minutes avant l'appel de prière, mais aussi de mettre à jour  input_datetime.next_salat_time. avec l'horaire de la prochaine prière 

Penser à rajouter dans configuration.yaml 
input_datetime:
  next_salat_time:
    name: next salat time
    has_date: true
    has_time: true
  next_prep_salat_time:
    name: next prep salat time
    has_date: true
    has_time: true




il suffit après de rajouter un sensor template dont la valeur est 

{{ ((as_timestamp(states("input_datetime.next_salat_time")) - (as_timestamp(now())))/60) | int }}


il permet de calculer combien de minutes nous sépare de la prochaine prière
[Blueprint-Mawaqit_Time_Notification.yaml.txt](https://github.com/mawaqit/home-assistant/files/8890576/Blueprint-Mawaqit_Time_Notification.yaml.txt)
