### ISSUE TITLE
erreur a l'installation

### ISSUE THREAD

**Issue by sator86** [mawaqit/home-assistant#21]
Salam aleykoum
une fois le repertoire copié, et apres avoir redemarré, j'ai cette erreur

`
Erreur

Cette intégration ne prend pas en charge la configuration via l'interface utilisateur. Si vous avez suivi ce lien depuis le site web de Home Assistant, assurez-vous que vous exécutez la dernière version de Home Assistant.``
`

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

barak'Allahou fikoum

**Comment by hajtux** [comment]
Wa'alaykoum Salam sator86, 

Pourrais-tu s'il te plait détailler où tu as copié le répertoire sur HA ? et quel répertoire tu as pris pour faire cette opération ?

**Comment by sator86** [comment]
oui biensur,
le repertoire "mawaqit" a été mis dans la répertoire "custom_components"
merci

**Comment by hajtux** [comment]
Pourrais-tu s'il te plaît ressayer avec la nouvelle version actuellement disponible ? Elle a été mise à jour récemment.  
Bien sûr bien supprimer l'ancienne version utilisée dans ton HA, redémarrer HA puis installer la nouvelle version. 

Tiens nous au courant !

**Comment by sator86** [comment]
c'est bon, ça a marché,
j'ai bien tous les horaires, mais quelque chose ne va pas, je ne sais pas si c'est lié au plugin ou à mon système
j'ai tous les horaires qui sont décalés de +1h 
pourtant j'ai bien mis la bonne mosquée et mon HA est bien configuré sur GMT+1 et sur ma ville avec la mosquée qui a toutes ses horaires  à -1h par rapport aux miennes
une idée ?
Merci

**Comment by hajtux** [comment]
Content d'apprendre que tout est rentré en ordre ^^ On peut donc clore cet issue. 
Je ne sais pas si tu peux le faire de ton côté directement. 
Wafika Baraka Allah
