### ISSUE TITLE
Heure du Djumua

### ISSUE THREAD

**Issue by DarkdroidHydro** [mawaqit/home-assistant#24]
Assalamou Aleykoum,
D'habitude, dans notre mosquée à Antony (92160) France, ID 112, nous avons 2 djumuas (12:05, 13:00), pendant les grandes vacances, nous avons 1 seule djumua à 13:00.

Avant HA nous donnait correctement l'heure du 1er djumua (12:05), mais depuis la suppression du 2ème djumua, HA n'arrive pas à se synchroniser avec Mawaqit et donne toujours 12:05 au lieu de 13:00 ! ce qui fausse les automatisations qui sont liées à l'heure du djumua.

les autres prières tout fonctionne très bien.

Baraka Allah fikoum.

**Comment by DarkdroidHydro** [comment]
Assalamou aleyloum,
Soubhana Allah, maintenant ça fonctionne très bien, j'ai modifié l'heure du Djumua dans Mawaqit, je recharge l'intégration dans HA et là l'heure de la Djumua est détectée instantanément !
Baraka Allah fikoum.

**Comment by hajtux** [comment]
Waalaykom ssalam @DarkdroidHydro 

Les changements exceptionnels d'heure de prière faits par les mosquées ne sont pas répercutées automatiquement dans l'intégration Mawaqit HA. 
Pour ce faire, et c'est ce que tu as fait, c'est recharger l'intégration une nouvelle fois. Voire dans certains cas la supprimer puis la réinstaller. 

En tout cas, content d'apprendre que c'est maintenant fonctionnel.
