### ISSUE TITLE
Only certain mosques showing up no matter what coordinates chosen

### ISSUE THREAD

**Issue by asdkjasdfla** [mawaqit/home-assistant#30]
I have added coordinates of a UK city but mosques in France are showing up. I have changed coordinates to another country but still the same mosques showing up. Any help?

![Screenshot_2023-04-05-21-58-36-068-edit_io homeassistant companion android](https://user-images.githubusercontent.com/81929959/230210099-89f2eb71-388a-4a0b-9871-96b1e41fed59.jpg)

**Comment by asdkjasdfla** [comment]
Just chosen Indian coordinates 31.3013511, 73.0334938 but still same mosques showing up
![Screenshot_2023-04-05-21-58-36-068-edit_io homeassistant companion android](https://user-images.githubusercontent.com/81929959/230210741-075f8d10-8876-4eda-a7e7-1e43e1c50427.jpg)

**Comment by hajtux** [comment]
Salamoalaykom, 

I think the easiest way to resolve this behavior is to:
- uninstall the mawaqit integration 
- delete the mawaqit folder in the custom_components directory of your homeassistant
- set your target coordination in your homeassistant
- download the last version of the mawaqit. Look at v2 in the branches. Install it as usual
- In the steps of configuration you should see the expected mosques.
 
I hope this helps you!

Regards,
Rachid

**Comment by mohaThr** [comment]
As-salamu aleykoum ! The problem has been solved and you no longer have to uninstall the integration or unload the entry :)
Just change your location on HomeAssistant settings and when you will click on "Configure" to change your mosque, the displayed mosques will be based on your new location ! I hope that you still use our H-A integration though
