### ISSUE TITLE
Refresh mawaqit

### ISSUE THREAD

**Issue by soofiane84** [mawaqit/home-assistant#31]
Bonjour,

Je tiens tout d'abord a vous remercier pour cette intégration.

J'ai installé hier mawaqit (v2) dans mon home assistant, j'ai bien récupéré les horaires de ma mosquée, mais le soir les horaires ne se sont pas actualisé, j'ai du redémarrer le serveur pour les actualiser.

Il y a t-il une solution sans redémarrer le serveur ?

BarakEllahou fikom

**Comment by hajtux** [comment]
Waalaykom Assalam Soufiane, 

Wa fika baraka Allah.
Normalement après l'installation d'une intégration sur Home Assistant, un redémarrage est nécessaire. 
Vous avez rencontré ce comportement uniquement après l'installation de Mawaqit ? vous continuez d'avoir le souci ? Ou bien les horaires se mettent à jour maintenant tous les jours et sans redémarrage. 

Rachid

**Comment by soofiane84** [comment]
Salam,

Non, ca se met pas à jour, il y a que le sensor next time qii se mets à jour.

Normalement les horaires ils se mettent a jour a près isha ou après minuit ? Ou a quelle moment ?

Merci beaucoup pour votre aide précieux.

**Comment by soofiane84** [comment]
Bonjour,

Alors les horaires se sont mise à jour à 5h du matin, c'est pas l'idéal mais ca marche bien. Merci pour votre aide.

Bien cordialement.

**Comment by MehdiTouns31** [comment]
Salemoua3laykoum, 

J'ai constaté dans mon installation que les horaires des 5 prières et du Shourouq se mettent à jour la minute qui suit l'horaire d'entrée de la prière du Fajr.
Ce qui signifie que le sensor adhan de la prière du Fajr est l'horaire du Jour N-1 au lieu d'être l'horaire du jour N.
Faites y particulièrement attention en ce mois du Ramadan où nous jeûnons dès l'entrée de la prière du Fajr...

Mehdi

**Comment by soofiane84** [comment]
> Salemoua3laykoum,
> 
> J'ai constaté dans mon installation que les horaires des 5 prières et du Shourouq se mettent à jour la minute qui suit l'horaire d'entrée de la prière du Fajr. Ce qui signifie que le sensor adhan de la prière du Fajr est l'horaire du Jour N-1 au lieu d'être l'horaire du jour N. Faites y particulièrement attention en ce mois du Ramadan où nous jeûnons dès l'entrée de la prière du Fajr...
> 
> Mehdi
Salam, 
Exactement, idéalement une actualisation juste après isha ça serait top. 

Merci.

**Comment by MehdiTouns31** [comment]
Oui par exemple, en espérant que ça puisse être résolu par nos chers développeurs !

En tout cas beau boulot pour la V2. Je n'ai quasi plus de bug sur les actualisations des horaires de prières.

Bonne fin de mois de ramadhan,
Mehdi

**Comment by hajtux** [comment]
Baraka Allaho fikoum. 

Nous sommes en train de voir pour identifier d'où vient ce bug qui est particulièrement important.
On vous tiendra au courant dès que c'est corrigé. 

En tout cas nous apprécions vos retours et remarques. C'est ce qui nous permet d'améliorer la qualité de Mawaqit de jour en jour. 

Bonne fin de mois de Ramadan. 
Qu'Allah accepte nos adorations.

Rachid

**Comment by soofiane84** [comment]
Barakellahou fikoom, hate de tester la nouvelle version. En attendant j'ai programme un restart a 3h du matin, et ca récupère bien les bons horaires.
Saha ftourkom.

**Comment by mohaThr** [comment]
Assalamu aleykoum ! Le problème réglé dans la V2.1 :)
