### ISSUE TITLE
Intégration Mawaqit KO après mise à jour 2023.5.0 

### ISSUE THREAD

**Issue by soofiane84** [mawaqit/home-assistant#33]
Bonjour,

Après la mise à jour core Home assistant à 2023.5.0, le plugin n'est plus opérationnel. En effet, l'attribut "async_setup_platforms"   utilisé dans le script _ini_.py ligne 368 est obsolète.

Pouvez-vous svp corriger ? 

`Logger: homeassistant.config_entries
Source: custom_components/mawaqit/init.py:368
Integration: Mawaqit
First occurred: 00:11:48 (1 occurrences)
Last logged: 00:11:48

Error setting up entry Mawaqit for mawaqit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mawaqit/init.py", line 87, in async_setup_entry
    if not await client.async_setup():
  File "/config/custom_components/mawaqit/init.py", line 368, in async_setup
    self.hass.config_entries.async_setup_platforms(self.config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

merci d'avance.

**Comment by hajtux** [comment]
Waalaykom ssalam. 

OK we will check on our side and let you know. 

Regards,
Rachid

**Comment by mouledla** [comment]
Same issue here. i am at 2023.5.2
