### ISSUE TITLE
Sensor next Salat Name + Time

### ISSUE THREAD

**Issue by sidi2181** [mawaqit/home-assistant#56]
السلام عليكم ورحمة الله وبركاته ،
يتم حساب الصلاة القادمة بالخطئ Next_salate_name /next_salat_time
بالمفروض يجب ان تكون الصلاة القادمة بعد الفجر هي الظهر وليس العصر
![IMG_3907](https://github.com/mawaqit/home-assistant/assets/155488337/7dd47573-296c-42c7-8232-1ed8a60cce6e)

**Comment by moha-tah** [comment]
This is fixed in the next version inshaAllah
